apiVersion: apps/v1
kind: Deployment
metadata:
    name: myschool-deployment-v3
    namespace: dev
spec:    
    replicas: 1
    selector:
      matchLabels:
        app: myschool-v3
    template:
      metadata:
        labels:
          app: myschool-v3
      spec:       
        containers:
        - name: myschool-v3
          image: kanu17/my-school-pupil:2.0.0
          envFrom:
           - secretRef:
               name: app-mongodb-credentials
          imagePullPolicy: Always 
          ports:
          - containerPort: 8002
