
apiVersion: v1
kind: Service
metadata:
  name: myschool-service-v3
  namespace: dev
  labels:
    app: myschool-v3
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: myschool-v3
  ports:
    - port: 80
      targetPort: 8002

